In [1]:
# Deliverable One. Open a new Jupyter Notebook and load CSV file into the Jupyter Notebook.

# Task 1: Download the BUS336_Signature_Term_Project_Starbucks_Beverage_Menu CSV file from either the 
# Projects/Assignments folder in Blackboard or the GitHub account provided. 
# Save the CSV file in your C:\Users\YOUR COMPUTER NAME FOLDER.

In [2]:
# Task 2: Import pandas as pd to work with a package that can process dataframes.
# ENTER CODE BELOW THIS LINE.
import pandas as pd

# Import the BUS336_Signature_Term_Project_Starbucks_Beverage_Menu.csv file using the pandas package.
# ENTER CODE BELOW THIS LINE.
df = pd.read_csv("BUS336_Signature_Term_Project_Starbucks_Beverage_Menu.csv")
df

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [3]:
# Task 3: Rename the Jupyter Notebook from Untitled to the following name convention: 
# LastName_FirstName_BUS 336_Signature_Term_Project. 

# The file will be stored in the your C:\Users\YOUR COMPUTER NAME FOLDER.

In [4]:
# Delivarable Two. Explore rows with all blank values and remove them.

# Task 1: Using the isnull and sum functions, check the total NaN entries for all columns in the dataframe.
# ENTER CODE BELOW THIS LINE.
df.isnull().sum()

Product_Name           1
Size                   1
Milk                   1
Whip                   1
Serving_Size_ml        1
Calories               1
Total_Fat_g            1
Saturated_Fat_g        2
Trans_Fat_g            1
Cholesterol_mg         1
Sodium_mg              1
Carbohydrates_g        1
Dietary_Fiber_g        1
Sugar_g                1
Protein_g              1
Vitamin_A_%DV          1
Vitamin_C_%DV          1
Calcium_%DV            1
Iron_%DV               1
Caffiene_milligrams    1
dtype: int64

In [5]:
# Task 2: View the dataframe with the head function.
# ENTER CODE BELOW THIS LINE.
df.head(15)

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,zero,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
5,Brewed Coffee - Decaf Pike Place® Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
6,Brewed Coffee - Decaf Pike Place® Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,20.0
7,Brewed Coffee - Decaf Pike Place® Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,25.0
8,Brewed Coffee - Decaf Pike Place® Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,30.0
9,Brewed Coffee Traveler - Decaf Pike Place® Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,15.0
10,Brewed Coffee - Medium Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,155.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Brewed Coffee - Medium Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,235.0
13,Brewed Coffee - Medium Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,310.0
14,Brewed Coffee - Medium Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,410.0

In [6]:
# Task 3: Remove the row with all blank entries.
# The how='all' will drop all rows with only NaN values. 
# ENTER CODE BELOW THIS LINE.
df1 = df.dropna(how='all')

In [7]:
# Task 4: Validate that the blank row(s) have been removed.
# Use the isnull and sum functions to validate that df2 has only one column remains with an NaN.
# ENTER CODE BELOW THIS LINE.
df1.isnull().sum()

Product_Name           0
Size                   0
Milk                   0
Whip                   0
Serving_Size_ml        0
Calories               0
Total_Fat_g            0
Saturated_Fat_g        1
Trans_Fat_g            0
Cholesterol_mg         0
Sodium_mg              0
Carbohydrates_g        0
Dietary_Fiber_g        0
Sugar_g                0
Protein_g              0
Vitamin_A_%DV          0
Vitamin_C_%DV          0
Calcium_%DV            0
Iron_%DV               0
Caffiene_milligrams    0
dtype: int64

In [8]:
# Deliverable Three. Explore the data types and correct any errors.

# Task One: Using the dtypes function, check the data types.
# ENTER CODE BELOW THIS LINE.
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   object
 1   Size                 1204 non-null   object
 2   Milk                 1204 non-null   object
 3   Whip                 1204 non-null   object
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   object
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(15), object(5)
memory usage: 197.5+ KB

In [9]:
# Task 2: Look for column with the incorrect data type, understand why it is incorrect, 
# and change it to the correct data type.

# In the dataframe, the Sugar_mg column has an incorrect string entry when it should be numeric. 
# A 0 value was entered as "zero". This will not result in a NaN, but Python will recognize this as a string. 
# We need to convert the string “zero” to an actual numerical 0. As a demonstration, we use the current dataframe that we are
# working with and use the index numbers to isolate the row and column. The iloc function helps us isolate that the entry
# zero is in the second row, 14th column (index positions 1 and 13). We set that cell value to the number 0 and it will change the "zero" to 0.
# Run the code and look compare the Sugar_g column in df1 to df and see how the "zero" turns into a 0.
df1.iloc[1,13] = 0
df1

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_milligrams
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78,19.0,30.0,2.0,60.0,2.0,0.0
1201,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65,16.0,15.0,2.0,60.0,20.0,0.0
1202,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67,17.0,25.0,2.0,60.0,20.0,0.0
1203,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69,6.0,0.0,2.0,15.0,0.0,0.0
1204,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71,6.0,8.0,2.0,15.0,0.0,0.0

In [10]:
# Change Suger_g type to float.
# ENTER CODE BELOW THIS LINE.
df1["Sugar_g"] = df1["Sugar_g"].astype(float)

C:\Users\zengo\AppData\Local\Temp\ipykernel_26192\892311576.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Sugar_g"] = df1["Sugar_g"].astype(float)

In [11]:
# Validate that the Sugar_g variable has been changed to a float.
# ENTER CODE BELOW THIS LINE.
df1.Sugar_g.dtypes

dtype('float64')

In [12]:
# Deliverable Four. Explore the NaN values and remove the row with any NaN values.

# Task 1: Using the info function, check for one NaN value.
# If the Non-Null Count has multiple “1204 non-null” entries, but one has a “1203 non-null” entry, 
# then that column still has a NaN value.
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1204 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1204 non-null   object
 1   Size                 1204 non-null   object
 2   Milk                 1204 non-null   object
 3   Whip                 1204 non-null   object
 4   Serving_Size_ml      1204 non-null   float64
 5   Calories             1204 non-null   float64
 6   Total_Fat_g          1204 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1204 non-null   float64
 9   Cholesterol_mg       1204 non-null   float64
 10  Sodium_mg            1204 non-null   float64
 11  Carbohydrates_g      1204 non-null   float64
 12  Dietary_Fiber_g      1204 non-null   float64
 13  Sugar_g              1204 non-null   float64
 14  Protein_g            1204 non-null   float64
 15  Vitamin_A_%DV        1204 non-null   float64
 16  Vitamin_C_%DV        1204 non-null   float64
 17  Calcium_%DV          1204 non-null   float64
 18  Iron_%DV             1204 non-null   float64
 19  Caffiene_milligrams  1204 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.5+ KB

In [13]:
# Task 2: Assign a new dataframe df2 and remove the row with the NaN entry from the Saturated_Fat_g column in df1.
# Drop any remaining rows that have an NaN.
# ENTER CODE BELOW THIS LINE.
df2 = df1.dropna()

In [14]:
# Task 3: Validate that it has been corrected.
# Run the info function.
# ENTER CODE BELOW THIS LINE.
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Name         1203 non-null   object
 1   Size                 1203 non-null   object
 2   Milk                 1203 non-null   object
 3   Whip                 1203 non-null   object
 4   Serving_Size_ml      1203 non-null   float64
 5   Calories             1203 non-null   float64
 6   Total_Fat_g          1203 non-null   float64
 7   Saturated_Fat_g      1203 non-null   float64
 8   Trans_Fat_g          1203 non-null   float64
 9   Cholesterol_mg       1203 non-null   float64
 10  Sodium_mg            1203 non-null   float64
 11  Carbohydrates_g      1203 non-null   float64
 12  Dietary_Fiber_g      1203 non-null   float64
 13  Sugar_g              1203 non-null   float64
 14  Protein_g            1203 non-null   float64
 15  Vitamin_A_%DV        1203 non-null   float64
 16  Vitamin_C_%DV        1203 non-null   float64
 17  Calcium_%DV          1203 non-null   float64
 18  Iron_%DV             1203 non-null   float64
 19  Caffiene_milligrams  1203 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.4+ KB

In [15]:
# Deliverable Five: Change a column name.

# Task 1: Assign the dataframe to df3 and using the rename function, change the Caffiene_milligrams column header 
# from the df2 dataframe to Caffiene_mg.
# ENTER CODE BELOW THIS LINE.
df3 = df2.rename(columns = {'Caffiene_milligrams':'Caffiene_mg'})

In [16]:
# Task 2: Validate that it has been corrected.
# ENTER CODE BELOW THIS LINE.
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1203 entries, 0 to 1204
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product_Name     1203 non-null   object
 1   Size             1203 non-null   object
 2   Milk             1203 non-null   object
 3   Whip             1203 non-null   object
 4   Serving_Size_ml  1203 non-null   float64
 5   Calories         1203 non-null   float64
 6   Total_Fat_g      1203 non-null   float64
 7   Saturated_Fat_g  1203 non-null   float64
 8   Trans_Fat_g      1203 non-null   float64
 9   Cholesterol_mg   1203 non-null   float64
 10  Sodium_mg        1203 non-null   float64
 11  Carbohydrates_g  1203 non-null   float64
 12  Dietary_Fiber_g  1203 non-null   float64
 13  Sugar_g          1203 non-null   float64
 14  Protein_g        1203 non-null   float64
 15  Vitamin_A_%DV    1203 non-null   float64
 16  Vitamin_C_%DV    1203 non-null   float64
 17  Calcium_%DV      1203 non-null   float64
 18  Iron_%DV         1203 non-null   float64
 19  Caffiene_mg      1203 non-null   float64
dtypes: float64(16), object(4)
memory usage: 197.4+ KB

In [17]:
# Deliverable Six: Describe the continuous and categorical data.

# Task 1: Using dataframe df3, use the describe() function to describe the continuous variables.

# Continuous variables obtain the measures of central tendency, such as the mean and median,
# as well as variance information such as standard deviations. 
# ENTER CODE BELOW THIS LINE.
df3.describe().round(2)

,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
count,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00,1203.00
mean,464.70,230.83,6.37,3.98,0.12,15.55,142.82,37.59,0.86,34.95,5.99,10.20,3.01,18.01,7.77,82.00
std,159.72,132.05,5.89,3.99,0.15,17.96,89.91,22.47,1.51,21.64,4.84,8.69,14.12,15.59,13.30,76.48
min,236.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,354.00,140.00,1.50,0.30,0.00,0.00,75.00,20.00,0.00,19.00,2.00,2.00,0.00,2.00,0.00,20.00
50%,473.00,220.00,5.00,3.00,0.00,5.00,135.00,35.00,0.00,33.00,5.00,10.00,0.00,15.00,0.00,75.00
75%,591.00,310.00,10.00,7.00,0.20,30.00,200.00,53.00,1.00,48.00,9.00,15.00,0.00,25.00,10.00,130.00
max,887.00,640.00,28.00,20.00,0.50,75.00,370.00,96.00,8.00,89.00,25.00,50.00,240.00,90.00,90.00,475.00

In [18]:
# Task 2: Using dataframe df3, use the describe() function to describe the categorical variables.

# Categorical variable to get the count of rows, unique count of categories, top category, and freq of top category.
df3.describe(include='object')

               Product_Name    Size    Milk     Whip
count                  1203    1203    1203     1203
unique                   94       7       6        2
top     White Hot Chocolate  Grande  Nonfat  No Whip
freq                     50     345     240      910

In [19]:
# Task 3: Analyze, interpret, and write about the continuous and categorical variables.

# There are a many observations to note about the continuous variables that your client maybe interested to hear. 
# Here are just a few continuous variable observations. Students can note different ones.
# The minimum size for any drink is 236 ml, which is about 8 ounces. The maximum is 887 ml, which is about 30 ounces.
# Could there be opportunities to serve smaller or larger drinks? Why did Starbucks choose these drink size ranges?
# Every nutritional measure has a minimum zero count. What could that indicate?
# There drinks tend to have more Cholestoral then less. Look at the 0% to 50% percentage compared to the 75% to 100%.

# There are a many observations to note about the categorical variables that your client maybe interested to hear. 
# Here are just a few categorical variable observations. Students can note different ones.
# There ar 1,203 different drink combinations. Aprpoximately 94 are unique product names. 
# What resources does it take to train its employees to know the products?
# White Hot Chocolate is the Product Name that is repeated most often. Why? 
# Grande seems to be the most popular size.
# Customers appear to prefer Nonfat milk and do not prefer Whip cream for drinks that have that option.
# There are six different types of Milk options. Nowadays, the Milk options on the market far exceed six. 
# Is there opportunity here?
# There are seven different sizes for drinks. Is this too many, too little, or just the right amount?

In [20]:
# Deliverable Seven: Write the dataframe to a CSV file, save it, and verify it as a CSV file.

# Task 1: Using the to_csv function, write dataframe df3 to a new df4.CSV file.
# ENTER CODE BELOW THIS LINE.
df3.to_csv('df4.csv', index=False)

In [21]:
# Task 2: 
# You do not have to make an entries to code anything for this task. Just check your file to make sure that df4 is saved.

In [22]:
# Task 3: Assign a new dataframe and load the CSV file back into the Jupyter Notebook using the pandas package. 
# ENTER CODE BELOW THIS LINE.
df4 = pd.read_csv('df4.csv')

In [23]:
# Task 4: Open the newly created CSV file in the Jupyter Notebook.
# ENTER CODE BELOW THIS LINE.
df4

,Product_Name,Size,Milk,Whip,Serving_Size_ml,Calories,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium_mg,Carbohydrates_g,Dietary_Fiber_g,Sugar_g,Protein_g,Vitamin_A_%DV,Vitamin_C_%DV,Calcium_%DV,Iron_%DV,Caffiene_mg
0,Brewed Coffee - Dark Roast,Short,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
1,Brewed Coffee - Dark Roast,Tall,No Milk,No Whip,354.0,4.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,193.0
2,Brewed Coffee - Dark Roast,Grande,No Milk,No Whip,473.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,260.0
3,Brewed Coffee - Dark Roast,Venti®,No Milk,No Whip,591.0,5.0,0.1,0.0,0.0,0.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,340.0
4,Brewed Coffee Traveler - Dark Roast,1 - 236 mL serving,No Milk,No Whip,236.0,3.0,0.1,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,130.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,White Hot Chocolate,Venti®,Whole,Whip,591.0,640.0,28.0,18.0,0.5,75.0,330.0,78.0,0.0,78.0,19.0,30.0,2.0,60.0,2.0,0.0
1199,White Hot Chocolate,Venti®,Soy,No Whip,591.0,470.0,14.0,7.0,0.0,5.0,290.0,69.0,2.0,65.0,16.0,15.0,2.0,60.0,20.0,0.0
1200,White Hot Chocolate,Venti®,Soy,Whip,591.0,540.0,21.0,11.0,0.2,30.0,300.0,71.0,2.0,67.0,17.0,25.0,2.0,60.0,20.0,0.0
1201,White Hot Chocolate,Venti®,Coconut,No Whip,591.0,450.0,17.0,15.0,0.0,5.0,310.0,71.0,0.0,69.0,6.0,0.0,2.0,15.0,0.0,0.0
1202,White Hot Chocolate,Venti®,Coconut,Whip,591.0,520.0,24.0,20.0,0.2,30.0,320.0,73.0,0.0,71.0,6.0,8.0,2.0,15.0,0.0,0.0

In [24]:
# Deliverable Eight: Upload file into your GitHub Account.

# Share your work with others! You do not need to do anything else inside this file. Anyone who has the file can replicate
# the work that you have done. They can modify it at will.
# Now you will be able to explain to anyone what you did and how you did it with a clean trail. 
# Try duplicating that feat in Excel!

# Task #1: Open your GitHub account and upload the newly created df4.csv file.
# Task #2: Validate that it has been uploaded and can be opened by emailing it to yourself and  instructor.

In [25]:
# Deliverable Nine: Make a short video explaining deliverables one through nine.

# Follow the instruction in the Step-by-Step guide to submit it.

# Task #1: Rehearse, record, and present a video presentation.
# Task #2: Upload the video presentation.

In [26]:
# Deliverable Ten: Write a reflection (in a separate Word document.

# Task #1: Write a reflection in the Python file.

Students write a reflection with a critical review of what you learned in the course and how Python can build a desired skill set. Be mindful to. I am very interested to hear the following:
•	Review the course learning objectives in the syllabus and discuss how you feel the course and the Signature Term Project achieved those objectives.
•	What you expected before you came into this class and what you think you are taking away from this class.
•	Your perception about Python and programming and how it may be able to help you better understand abstract business information and develop your skill set. What was easy and challenging as far as learning actual programming? Why Is Python interesting to you? Did Datacamp help you? 
•	What would you have like to have learned that was not covered?
•	How could the directions be clearer for the Signature Term Project? 
•	Do you think that the hints made the project less challenging? Without them, do you think that you could have completed the project by the conclusion of the semester?
•	Did you think that understanding GitHub was important? Although we did not even come close to understanding its capabilities, from your exposure do you think it will become one of your tools to communicate workflows? How will you use it? 
•	Do you plan to study Python further? How?

I am looking forward to your reflections and I read every word that you write!

# Task #2: Open your GitHub account and upload the newly created Jupyter Notebook Source File (.ipynb) file.

Sign into your GitHub account and go into your repository that contains your newly created Jupyter Notebook Source File (.ipynb) file. Click on the  icon and choose upload files. Once you choose your file from the C:\Users\YOUR COMPUTER NAME FOLDER, in GitHub make sure that you scroll down the page and hit the   icon to complete the upload. The file should now be in your repository to share with the world. To share the file, click on the file name and copy the URL.

# Task #3: Email the GitHub links to yourself, your instructor and upload it into Blackboard.

For this task:

1.	Email the GitHub link to yourself.
2.	Email the GitHub link to your instructor.
3.	Upload it into Blackboard so it can be graded.

Start typing your reflection below this paragraph. You do not have to include a hash tag to begin the line as you did in Deliverable Six. 
Just start typing and make sure that you put in line breaks when you get close to the right margin like you see here.
Try to hit the run button for this code block. You will get an SyntaxError message. Do not worry about it. I can still read 
your reflection. I just want you to see the difference if you type a narrative with or without a #.

# ENTER Reflection BELOW THIS LINE.

SyntaxError: invalid character '•' (U+2022) (3549547038.py, line 6)